### ISSUE TITLE
Insufficient credits

### ISSUE THREAD

**Issue by DariaProvogance** [aaroniker/figma-remove-bg#4]
Hi! For some time now I keep getting this error message. Can`t find anywhere what does "insufficient credits" mean. Is there a way to fix this?
![Screenshot_20](https://user-images.githubusercontent.com/65905062/82818738-d47e5e80-9ea7-11ea-9830-08d99f2b5263.png)

**Comment by aaroniker** [comment]
Thanks for your issue!
This plugin uses the remove.bg API - seems that you are out of credits.
More here https://www.remove.bg/pricing
