### ISSUE TITLE
Often fails with "There was an error reading the image"

### ISSUE THREAD

**Issue by banar** [aaroniker/figma-remove-bg#9]
![example-figma-remove-bg-error-image](https://user-images.githubusercontent.com/465261/109432492-6d16b180-79d9-11eb-8768-8e6bb473ee6d.jpg)
Example file that's failing attached!

**Comment by aaroniker** [comment]
Thanks for your report!
Got a lot of messages about that lately - will try to fix :)

**Comment by irensaywhen** [comment]
The same here. Are there any updates on this issue?

**Comment by aaroniker** [comment]
Should be fixed now
